---
apiVersion: v1
kind: Template
metadata:
  name: hcc-ai-assistant
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: hcc-ai-assistant
    spec:
      envName: ${ENV_NAME}
      database:
        name: hcc-ai-assistant
      featureFlags: true
      kafkaTopics:
      # one replica for now; most of this will change
      - replicas: 1
        partitions: 8
        topicName: platform.chrome
      deployments:
      - name: api
        minReplicas: ${{MIN_REPLICAS}}
        webServices:
            public:
              apiPath: hcc-ai-assistant
              enabled: true
        podSpec:
          image: ${IMAGE}:${IMAGE_TAG}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumes:
          - name: vertex-api
            secret:
              secretName: vertex-api
          volumeMounts:
          - name: vertex-api
            mountPath: /opt/secrets
            readOnly: true
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 4Gi
          env:
          - name: LIGHTSPEED_STACK_CONFIG_PATH
            value: ${LIGHTSPEED_STACK_CONFIG_PATH}
          - name: VERTEX_PROJECT
            value: ${VERTEX_PROJECT}
          - name: VERTEX_LOCATION
            value: ${VERTEX_LOCATION}
          - name: ALLOWED_MODEL
            value: ${ALLOWED_MODEL}
          - name: VERTEX_SECRET_PATH
            value: ${VERTEX_SECRET_PATH}
          - name: STORAGE_DIR
            value: ${STORAGE_DIR}
          - name: KV_STORE_PATH
            value: ${KV_STORE_PATH}
          - name: SQL_STORE_PATH
            value: ${SQL_STORE_PATH}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: ${VERTEX_SECRET_PATH}
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: EMBEDDING_SERVICE_PORT
            value: "8002"
          - name: MCP_DISCOVERY_SERVICE_PORT
            value: "8001"
          - name: ENABLE_VECTOR_STORE
            value: "true"
parameters:
- name: VERTEX_PROJECT
  required: true
- name: VERTEX_LOCATION
  required: true
- name: ALLOWED_MODEL
  required: true
- name: VERTEX_SECRET_PATH
  value: /opt/secrets/service-account-json
- name: LIGHTSPEED_STACK_CONFIG_PATH
  value: /app-root/lightspeed-stack.yaml
- name: STORAGE_DIR
  value: /tmp/data/storage/files
- name: KV_STORE_PATH
  value: /tmp/data/storage/rag/kv_store.db
- name: SQL_STORE_PATH
  value: /tmp/data/storage/sql_store.db
- name: MIN_REPLICAS
  value: '3'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/lightspeed-core/lightspeed-stack
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  required: true
